2025-04-20 20:56:54.611 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-04-20 20:57:06.229 WARNING (MainThread) [homeassistant.components.mqtt.light.schema_json] Invalid brightness value '100' received for entity light.living_room_light
2025-04-20 20:57:20.624 WARNING (MainThread) [homeassistant.core] Something is blocking Home Assistant from wrapping up the start up phase. We're going to continue anyway. Please report the following info at https://github.com/home-assistant/core/issues: history, network, sensor, ssdp, climate, backup.sensor, homeassistant, stt, webhook, mqtt, media_source, http, usb, websocket_api, logger, repairs, api, input_boolean, light, hacs.switch, input_number, mqtt.device_tracker, google_translate, dhcp, hacs, update, assist_pipeline, wake_word, onboarding, backup, mqtt.climate, stream, google_translate.tts, persistent_notification, mobile_app.notify, counter, default_config, cloud.tts, mqtt.sensor, scene, input_button, config, script, application_credentials, system_health, schedule, shopping_list.todo, switch, image_upload, hardware, frontend, logbook, recorder, device_automation, system_log, intent, input_text, lovelace, person, trace, device_tracker, lock, radio_browser, sun, shopping_list, homeassistant_alerts, hacs.update, diagnostics, bluetooth, input_datetime, automation, sun.sensor, tag, mobile_app, zone, notify, my, mqtt.light, go2rtc, timer, input_select, file_upload, auth, ffmpeg, cloud, conversation, blueprint, energy, homeassistant.scene, tts, todo, zeroconf, mqtt.lock, analytics, camera, search, energy.sensor The system is waiting for tasks: {<Task pending name='Task-97' coro=<HacsBase.startup_tasks() running at /config/custom_components/hacs/base.py:666> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[set.remove()]>}
2025-04-20 20:57:50.687 ERROR (MainThread) [homeassistant.components.homeassistant_alerts.coordinator] Timeout fetching homeassistant_alerts data
2025-04-20 20:59:06.683 ERROR (MainThread) [custom_components.hacs] Could not update theme - Timeout of 60s reached
2025-04-20 20:59:06.684 ERROR (MainThread) [custom_components.hacs] Could not update plugin - Timeout of 60s reached
2025-04-20 20:59:06.684 ERROR (MainThread) [custom_components.hacs] Could not update template - Timeout of 60s reached
2025-04-20 20:59:06.685 ERROR (MainThread) [custom_components.hacs] Could not update integration - Timeout of 60s reached
2025-04-20 21:06:57.834 WARNING (MainThread) [homeassistant.components.light] light.living_room_light (<class 'homeassistant.components.mqtt.light.schema_json.MqttLightJson'>) does not report a color mode, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
2025-04-20 21:12:50.627 ERROR (MainThread) [homeassistant.components.analytics] Timeout sending analytics to https://analytics-api.home-assistant.io/v1
2025-04-20 21:21:12.014 ERROR (MainThread) [homeassistant.components.automation.get_home_member] Get Home member: Error executing script. Invalid data for call_service at pos 1: two or more values in the same group of exclusion 'brightness' @ data[<brightness>]
2025-04-20 21:21:12.014 ERROR (MainThread) [homeassistant.components.automation.get_home_member] Error while executing automation automation.get_home_member: two or more values in the same group of exclusion 'brightness' @ data[<brightness>]
2025-04-20 21:22:35.860 ERROR (MainThread) [homeassistant.components.automation.get_home_member] Get Home member: Error executing script. Invalid data for call_service at pos 1: two or more values in the same group of exclusion 'brightness' @ data[<brightness>]
2025-04-20 21:22:35.860 ERROR (MainThread) [homeassistant.components.automation.get_home_member] Error while executing automation automation.get_home_member: two or more values in the same group of exclusion 'brightness' @ data[<brightness>]
2025-04-20 21:23:46.225 ERROR (MainThread) [homeassistant.components.automation.get_home_member] Get Home member: Error executing script. Invalid data for call_service at pos 1: two or more values in the same group of exclusion 'brightness' @ data[<brightness>]
2025-04-20 21:23:46.225 ERROR (MainThread) [homeassistant.components.automation.get_home_member] Error while executing automation automation.get_home_member: two or more values in the same group of exclusion 'brightness' @ data[<brightness>]
